# Generated by Django 3.1.4 on 2021-01-17 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0029_auto_20210116_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='image',
        ),
    ]
