# Generated by Django 3.1.4 on 2021-02-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0033_auto_20210214_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
