# Generated by Django 3.0.8 on 2020-12-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201111_1426'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='codevalue',
            name='cv_code_set_idx',
        ),
        migrations.AddIndex(
            model_name='codevalue',
            index=models.Index(fields=['code_set', 'definition'], name='cv_code_set_idx'),
        ),
    ]
