# Generated by Django 3.1.4 on 2021-07-25 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201226_1138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeValueSet',
            new_name='CodeSet',
        ),
        migrations.AlterField(
            model_name='codevalue',
            name='code_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_values', to='core.codeset'),
        ),
        migrations.AlterModelTable(
            name='codeset',
            table='core_code_set',
        ),
    ]
