# Generated by Django 3.0.8 on 2020-09-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonImport',
        ),
    ]
