# Generated by Django 3.0.8 on 2020-11-11 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20201111_1426'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('active_ind', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('create_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('create_id', models.BigIntegerField(default=0)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('updt_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'shop_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('create_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('create_id', models.BigIntegerField(default=0)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('updt_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'shop_cart_item',
                'ordering': ('product',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('active_ind', models.BooleanField(default=True, verbose_name='Active')),
                ('create_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('create_id', models.BigIntegerField(default=0)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('updt_id', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'shop_category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('create_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('create_id', models.BigIntegerField(default=0)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('updt_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'shop_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('create_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('create_id', models.BigIntegerField(default=0)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('updt_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'shop_order_item',
                'ordering': ('product',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('create_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('create_id', models.BigIntegerField(default=0)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('updt_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'shop_payment',
                'ordering': ('-create_dt_tm',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('display', models.CharField(max_length=100)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('active_ind', models.BooleanField(default=True, verbose_name='Active')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('create_dt_tm', models.DateTimeField(auto_now_add=True)),
                ('create_id', models.BigIntegerField(default=0)),
                ('updt_cnt', models.IntegerField(default=0)),
                ('updt_dt_tm', models.DateTimeField(auto_now=True)),
                ('updt_id', models.BigIntegerField(default=0)),
                ('category_cd', models.ForeignKey(limit_choices_to={'active_ind': 1, 'code_set': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.CodeValue', verbose_name='Category')),
            ],
            options={
                'ordering': ('name',),
                'permissions': (('can_load_shop_data', 'can load shop data'),),
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['description'], name='shop_paymen_descrip_e4adf0_idx'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shop.Payment', verbose_name='Order'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='shop_catego_name_289c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='shop_catego_slug_5ac49f_idx'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='p_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['display'], name='p_display_idx'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment'], name='shop_order_payment_49f7f9_idx'),
        ),
    ]
